### PR TITLE
Remove need for CGO

### PR DESCRIPTION
**Pull request by SuperQ**
Switch sqlite database driver to one that does not require CGO. This eliminates the need for dealing with dynamic and static compile options.
* Build with CGO_ENABLED=0.
* Update Go version in README based on `go.mod` version.

### CODE REVIEW

**Comment by SuperQ** [comment]
I guess I need to make some additional changes to the driver integration.

**Review by nsheridan — APPROVED** [review]
Delightful

**Comment by SuperQ** [comment]
One thing that would be useful, it seems GH actions are disabled for forked PRs. So we don't see the failure result here.

**Comment by nsheridan** [comment]
Huh. I've set it so approval is required to run actions for people outside the organisation but I can't see any option anywhere to run the workflows for this PR.
Maybe a force-push will kick something off?

**Comment by nsheridan** [comment]
The failure cause seems to be twofold:
First off, the CGO sqlite3 library declares its driver name as "sqlite3". The modernc library declares its driver name as "sqlite". The fix for this is simple enough: change all occurrences of "sqlite3" to "sqlite" in cashier, including the migrations directory name. 

The next problem is the [sql-migrate](https://github.com/rubenv/sql-migrate) library, which Cashier uses to execute migrations on process startup. That only supports the sqlite3 CGO library.

**Comment by SuperQ** [comment]
Boo, I guess we would need another migration tool, or to update the upstream library to support `modernc.org/sqlite`.

**Pull request closed without merging**
